#!/usr/bin/env bash
#prints "Best School" 10 times, "Hi" on the 9th
i=1
while [ $i -le 10 ]
do
    if [[ $i -eq 9 ]]
    then
        echo "Hi"
    else
        echo "Best School"
    fi
    ((i++))
done
